export const certificates = [
  "BUSINESS ENTERPRISE",
  "CIVIC ENGAGEMENT",
  "COOPERATIVE ENGINEERING EDUCATION PROGRAM",
  "INTEGRATED MARKETING COMMUNICATIONS",
  "KELLOGG PROGRAM FOR UNDERGRADUATES",
  "LEADERSHIP",
  "MANUFACTURING & DESIGN ENGINEERING (BS-MADE)",
  "MUSIC THEATRE",
  "SEGAL DESIGN",
  "SUSTAINABILITY AND ENERGY"
];
