export const minors = [
  "AFRICAN AMERICAN STUDIES",
  "AFRICAN STUDIES",
  "AMERICAN STUDIES",
  "ANTHROPOLOGY",
  "APPLIED MATHEMATICS",
  "ARCHITECTURAL ENGINEERING AND DESIGN",
  "ART HISTORY",
  "ARTS ADMINISTRATION",
  "ART THEORY AND PRACTICE",
];
