const waitlistEmails = [
  "seanpark2024@u.northwestern.edu",
  "luciusveiga2023@u.northwestern.edu",
  "alyssablanco2025@u.northwestern.edu",
  "Jacksondarby2023@u.northwestern.edu",
  "anthonykang2024@u.northwestern.edu",
  "jacksonbremen2024@u.northwestern.edu",
  "yong-yuhuang2026@u.northwestern.edu",
  "ZackSiedlecki2024@u.northwestern.edu",
  "markoveljanovski2025@u.northwestern.edu",
  "elijahhuang2024@u.northwestern.edu",
  "richardzimring2024@u.northwestern.edu",
  "alexandersorensen2025@u.northwestern.edu",
  "srimannarayanan2024@u.northwestern.edu",
  "richardli2024@u.northwestern.edu",
  "sydneyhogan2024@u.northwestern.edu",
  "derekyu2024@u.northwestern.edu",
  "kamiladominikowski2026@u.northwestern.edu",
  "ruthdebono2026@u.northwestern.edu",
  "Skylerstone2025@u.northwestern.edu ",
  "Elenahubert2025@u.northwestern.edu",
  "daniellee2025@u.northwestern.edu",
  "isaacmiller2024@u.northwestern.edu",
  "justindong2025.1@u.northwestern.edu",
  "laurenlee2025@u.northwestern.edu",
  "kellymei2024@u.northwestern.edu",
  "Lingxiaoshi2023@u.northwestern.edu",
  "brunodeclerck2025@u.northwestern.edu",
  "andyxu2023@u.northwestern.edu",
  "mseckykoebel@gmail.com",
  "vishaal.mali98@gmail.com",
  "AnirudhPoranki2024@u.northwestern.edu",
  "tiffanylou2024@u.northwestern.edu",
  "dustin.levell@northwestern.edu",
  "pdhanoa@u.northwestern.edu"
];

export { waitlistEmails };
