version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/"
    open-pull-requests-limit: 5
    # reviewers:
    #   - "mseckykoebel"
    schedule:
      interval: "daily"
    labels: 
      - "dependencies"
      - "automerge"
